import React, { useState } from 'react'
import LazyLoad from 'react-lazy-load'
import ImageLoader from '../ImageLoader/ImageLoader'
import './ImagesList.css'

const images = [
  {
    src:
      'https://images.wallpaperscraft.ru/image/origami_raznotsvetnyj_geometriia_170286_300x168.jpg',
  },

  {
    src:
      'https://images.wallpaperscraft.ru/image/nochnoj_gorod_arhitektura_zdanii_170285_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/derevo_zvezdnoe_nebo_vecher_170283_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/iahta_more_nebo_170282_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/zdanie_arhitektura_neboskreb_170281_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/sushchestvo_podvodnyj_mir_akvalang_170279_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/nadezhda_nadpis_slovo_170278_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/gory_skaly_poberezhe_170277_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/pirozhnoe_desert_zhasmin_170275_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/lvitsa_bolshaia_koshka_zver_170274_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/nebo_zakat_oblaka_170273_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/ptitsa_krylia_oblaka_170271_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/dzhojstik_gejmpad_pattern_170270_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/mclaren_570gt_mclaren_sportkar_170268_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/chelovek_odinochestvo_odinokij_170267_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/kalejdoskop_fraktal_krug_170266_300x168.jpg',
  },

  {
    src:
      'https://images.wallpaperscraft.ru/image/lodka_okean_voda_170264_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/ananas_listia_chb_170261_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/prerii_dolina_kamni_170259_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/gorod_zdaniia_gory_170258_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/tsvetok_zheltyj_lepestki_170257_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/domik_skazka_pejzazh_170255_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/gory_voda_doroga_170254_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/kaktus_koliuchki_rastenie_170253_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/telefon_ruka_kamera_170251_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/siluet_odinochestvo_odinokij_170250_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/audi_mashina_rul_170249_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/treugolniki_fragmenty_obem_170247_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/arhitektura_zdanie_fasad_170246_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/solntse_zakat_pliazh_170245_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/zhurnal_ochki_dzhinsy_170242_300x168.jpg',
  },

  {
    src:
      'https://images.wallpaperscraft.ru/image/noch_luna_vodopad_170241_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/kraski_zhivopis_razvody_170240_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/poberezhe_zakat_gorizont_170238_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/grani_fragmenty_geometriia_170237_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/vyhod_slova_ieroglify_170236_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/pankejki_desert_klubnika_170234_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/siren_tsvety_tsvetenie_170232_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/ckejtbord_skejt_ruka_170230_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/atom_koltsa_kamni_170227_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/okean_volny_bryzgi_170225_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/ogon_iskry_ugol_170223_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/pliazh_zakat_luchi_170220_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/zarianka_ptitsa_peria_170219_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/glitsiniia_tsvetok_rastenie_170217_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/jeep_wrangler_jeep_vnedorozhnik_170216_300x168.jpg',
  },

  {
    src:
      'https://images.wallpaperscraft.ru/image/zvezdnoe_nebo_zvezdy_vetki_170215_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/puzyri_voda_kruglyj_170213_300x168.jpg',
  },
  {
    src:
      'https://images.wallpaperscraft.ru/image/elektrogitara_gitara_muzykalnyj_instrument_170212_300x168.jpg',
  },
]

const ImagesList = () => {
  return (
    <div className="container">
      {images.map((img, i) => (
        <LazyLoad
          key={i}
          debounce={false}
          throttle={250}
          offsetVertical={300}
          className={'image'}
          onContentVisible={() => console.log(i)}
        >
          <ImageLoader src={img.src} alt={'imageLoader'} className={''} />
        </LazyLoad>
      ))}
    </div>
  )
}

export default ImagesList
